### ISSUE TITLE
Planning the UI Viewer Web-App Stack

### ISSUE THREAD

**Issue by lichtefeld** [isi-vista/adam#1024]

**Comment by gayatri1205** [comment]
Pros of using Angular:

- Has been used before in this environment
- Good maintainability
- Need to use lesser number of third party libraries, since most of the features come built in
- Better compatibility with an evolved backend
- Easy unit and end-to-end testing
- Angular-CLI enables quicker expansion of projects

Cons of using Angular:

- Will reload the complete tree structure of the HTML tags, which will cause a delay in application loading
- Will not work in browsers that have deactivated JavaScript

**Comment by gayatri1205** [comment]
Pros of using React:

- Highly performant due to component lazy loading
- One direction data flow
- Smaller code base to maintain

Cons of using React

- Unstructured, which makes it tough to maintain
- HTML mixed with JavaScript (JSX), which will make it harder to differentiate and read
- Can't reuse previously written Angular code if needed
- Will have to extensively make use of third party libraries

**Comment by lichtefeld** [comment]
@denizbeser Do you have any thoughts on the front-end framework? We should look to make a decision this week so progress can get started on implementation.

**Comment by denizbeser** [comment]
I read a bit about each and frankly I have close to no experience with both. What we need is to be able to display scenes and regions over them in hierarchical manners, and to be able to interact with these through some selectors and buttons. I'm sure both of these would easily work fine for that type of UI. I think it's up to @gayatri1205 to decide which one is easier for her to work with.

**Comment by gayatri1205** [comment]
Angular pretty much sounds like the best option to me as it has been used in this environment before and is quite maintainable when it comes to larger code bases.

**Comment by denizbeser** [comment]
Sounds great!

**Comment by lichtefeld** [comment]
Sounds good! @gayatri1205 -- Can you add a PR which adds an angular project to this repo and includes the appropriate setup instructions? You can place the angular project folder in the root of the repo in an 'angular-viewer' folder. 

#1025 is a good place to start for the display elements.

**Comment by gayatri1205** [comment]
Will do!

**Comment by gayatri1205** [comment]
@lichtefeld should I also edit the ReadME with instructions on how to run the angular app?

**Comment by lichtefeld** [comment]
Yes please add those instructions.

**Comment by lichtefeld** [comment]
Closing this as a Flask Backend with Angular Front-end has been established.
