### ISSUE TITLE
Handle core vocabulary verb: Come

### ISSUE THREAD

**Issue by denizbeser** [isi-vista/adam#200]
Come (~1500): almost always with directional/locational PP/ADVP (~1200; more including idioms e.g., “come on”), occasionally taking VP 

Come: almost all directional

**Comment by rgabbard** [comment]
@LichMaster98 : for the initial templates, just do a bare _X comes_ without the PP/ADVP because we don't have the right prepositions yet.  Make a separate issue for handling those modifiers.

For now, treat the distinction between _go_ and _come_ as that for _come_, the path must be towards the speaker (or if no speaker, towards the learner, let's say; make two separate templates)
