### ISSUE TITLE
Unless otherwise specified, objects should be on the ground

### ISSUE THREAD

**Issue by mitchmarcus** [isi-vista/adam#240]
Looking at the simplest one object contexts, ground_0 exists as does the object, but the relation between them seems undefined.  Does this matter?

**Comment by rgabbard** [comment]
Yes, things ought to have some relationship to the ground.  The trick is determining automatically exactly when to assert it.  I think we can get 90% of the way there by asserting that an object rests on the ground unless some other region is specified for it.  This isn't quite right, because it could be specified as e.g. _beside_ another object, but it is probably good enough for the M3 checkpoint.
