### ISSUE TITLE
Two babies of indeterminate size

### ISSUE THREAD

**Issue by mitchmarcus** [isi-vista/adam#248]
You don't say anything about the relative size of the two babies.  This might be fine, but might also be a symptom that only entity pieces have sizes, not top-level entities, if that's the way the code is written.

**Comment by rgabbard** [comment]
@mitchmarcus : Currently the size relationships come from two places:
* they can be explicitly specified by the situation template author
* they are implied by the object type.  So for example, a `house` will be bigger than a `ball` whether the user specifies it or not.
* they are implied by the semantics of the verbs being used.

This means that unless specified, we don't encode size relations between objects of the same type yet.  We do want to do this ( https://github.com/isi-vista/adam/issues/251 ), though, because otherwise we "sneak" some signal to the learner about what is relevant and what is not in the situation.
