### ISSUE TITLE
Should "Dad gives Dad a House" be a valid situation?

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#270]
See Scene 5 from `006 - transfer-of-possession.html` for the example. But per my discussion with Marjorie it doesn't make sense that Dad should be able to give Dad something.

**Comment by rgabbard** [comment]
This should not happen. In template generation we should filter out any situation which would have the same `RECOGNIZED_PARTICULAR` instantiated twice

**Comment by mitchmarcus** [comment]
For much later, note that this is what reflexives allow "Dad gave himself the biggest piece of cake."
So it does make conceptual sense potentially.

**Comment by rgabbard** [comment]
@mitchmarcus : We actually do support something like `Dad have himself the biggest piece of cake` in our semantic representation (except our language generation module will choke on it for now, since it doesn't know about reflexives).  The bug here is that it was actually trying to say simultaneously that there were two different entities in the situation, but they were both the recognized particular `Dad`
