### ISSUE TITLE
Template for two people throwing things to each other.

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#318]
I expect problems with binding two manipulators in a scene, which is why this is split off from #208.

**Comment by elizlee** [comment]
The complications with enabling `PERSON throws THEME to PERSON` start with not being able to handle more than one manipulator. This seems to happen in part because the relevant `ActionDescription` of `THROW` only has one `THROW_MANIPULATOR` (see [here](https://github.com/isi-vista/adam/blob/0474a9dbd0ecf3d833e73b010abac120014c7872/adam/ontology/phase1_ontology.py#L2007)).

So it seems that the first part of the solution is creating a new `ActionDescription` for this situation that takes a second manipulator (say, `CATCH_MANIPULATOR`), but since such a description has the same semantic roles as the original ({agent, theme, goal}), they cannot be distinguished from each other (handled [here](https://github.com/isi-vista/adam/blob/0474a9dbd0ecf3d833e73b010abac120014c7872/adam/ontology/ontology.py#L231)).

This makes me think that one way around this could be to add, perhaps, an optional `tag` variable to `ActionDescription` and somehow use it to help determine which one is appropriate to use for a particular situation. In this case, `required_action_description` would check if the `GOAL` filler is a `Region` - if not a region, the `GOAL` should be the animate object catching the thrown object, and the `ActionDescription` with the appropriate tag (like "two_manipulators") should be returned.

There could be a far simpler alternative that I'm not seeing. Any thoughts on this?

**Comment by elizlee** [comment]
Another I was thinking of, if allowable, would be to create a new semantic role for this purpose, like `GOAL_REGION` (maybe as a subtype of `GOAL`).

**Comment by gabbard** [comment]
@elizlee : Leave `X throws to Y` aside for right now.
