### ISSUE TITLE
Change debug string of table legs to be "table (leg)" like "animal (leg)" is

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#441]

**Comment by LichMaster98** [comment]
@gabbard It's worth noting that a `chair` object will also then have sub-parts with the debug label of "table (leg)" which is why I originally chose `inanimate` as the descriptor. That said, we could just create an additional ontologyNode that has a debug string of `chair (leg)`.

**Comment by gabbard** [comment]
@LichMaster98 : Is the current debug string `leg (inanimate)`?

**Comment by LichMaster98** [comment]
@gabbard The debug strings for the `ontologyNode` objects are "(animal) leg" and "(inanimate) leg". I suppose it's worth asking which debug string Mitch was commenting on? I made the assumption it was the `ontologyNode` debug string.

**Comment by gabbard** [comment]
@LichMaster98 : He said this concerning Scene 19 in the curriculum you sent him: 

> I assume that _(animal) leg_ is giving the type of leg somehow - that there are animal legs and table legs, which are also legs. (But then why not _(table) leg_ in some of the examples above?

Can you do a quick glance at the curriculum to see if you see any unspecified legs?

**Comment by LichMaster98** [comment]
@gabbard All the legs in the perception appear with either "(animal) leg_0" or "(inanimate) leg_0" where 0 is a unique identifier for the perception debug. Mom (In Scene 19 of the "on" preposition) has 2 animal legs "(animal) leg_0" and "(animal) leg_1" while the chair in the scene has "(inanimate) leg_0", "(inanimate) leg_1", "(inanimate) leg_2", and "(inanimate) leg_3." I believe the perception debug handles are generated from the ontologyNode debug handle. Leg has this additional identifier for deug because the animal leg has a sub-part object schema while the table leg does not. (We needed to give our humans legs with two bones and a foot while a table or chair's leg doesn't have the same sub-part structure) 

We are giving the type of the leg away for debug purposes so it is easier for the human reader to understand which "leg" should be referenced when reading the scene.

**Comment by LichMaster98** [comment]
@gabbard For this issue, did we decide if "(inanimate) leg" and "(animate) leg" were appropriate debug strings for the usages of the two different 'leg' ontology nodes? (One being a leg for an animal and the other being a leg of a table/chair)

**Comment by gabbard** [comment]
Do we use "inanimate leg" anywhere besides `table`?

**Comment by LichMaster98** [comment]
We use it for `chair`

**Comment by gabbard** [comment]
Maybe `leg (furniture)` then?
