### ISSUE TITLE
Should content-identical Region objects be collapsed together?

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#444]
Should content-identical Region objects be collapsed together?  Currently `Regions` have the funny property that the are treated as value objects (meaning content-identical regions will compare equal) everywhere in the code, except when building perception graphs, where they are distinguished by the object ID (because the `Region` itself forms the graph node, the reference object is split off into another node connected to it by an edge).  

Should we collapse `Region` objects which are identical together everywhere?  Does it matter one way or another for anything?

**Comment by LichMaster98** [comment]
The best spot to do region collapsing/merging is probably right after we perceive relationships in `high_level_semantics_situation_to_developmental_primitive_perception.py` because we do the addition of implicit relations in during this process. For example, we add the relationship between objects and the ground. 

I can't think of a reason why collapsing this information would cause issues, preposition patterns should still be able to eliminate the non-relevant directional information from the memory pattern.

**Comment by gabbard** [comment]
I think the answer here is no, because we are using a node-induced and not edge-induced subgraph isomorphism algorithm.
