### ISSUE TITLE
How to deal with hierarchical object recognitions without allowing overlapping object recognitions?

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#502]
When getting the preposition subset learned to work with a less controlled curriculum, I ran into the problem where some of the object recognitions were overlapping, resulting in weird edges in the post-recognition graph like one "recognized object" node being marked as a component of another one (when neither object was actually a component of another).

In https://github.com/isi-vista/adam/pull/501, I modified the object recognizer to delete the nodes which make up a recognized object from the graph, which eliminates the problem above. However, it does create another problem: we can no longer recognize objects which truly are a part of another object, like hands being a part of people.

I think the correct solution here is do do all the matches without deletion, then do all the matched node insertions and deletions jointly, so that we can make explicit decisions about overlaps and create relationships appropriately for hierarchical objects.

**Comment by denizbeser** [comment]
@gabbard your modification in #501 makes sense to me actually. I typically see our implementation of object recognition as the "whole object perception" primitive in humans, which wouldn't necessarily capture sub-objects like hand, as they're just a part of some other whole.

**Comment by gabbard** [comment]
@denizbeser : Can you think about this problem and make some suggestions? (but don't code anything yet)

**Comment by denizbeser** [comment]
@gabbard can you give an example of the overlapping objects case? or point me to the curriculum example that caused the problem?

**Comment by gabbard** [comment]
@denizbeser : for example, we can recognize both a human person and a person's hand.  But our current object recognition node replaces all the recognized portion of the graph with a single "recognized object" node. If either the person or hand patterns match first, the second will fail to match.

This matters because we want to be able to say things like _The bird is on the head_

**Comment by denizbeser** [comment]
Got it, thanks. I will look into it.

**Comment by gabbard** [comment]
@denizbeser : can you return to thinking about this problem?

**Comment by denizbeser** [comment]
@gabbard using the _The bird is on the head_ example you mentioned above, I'm assuming we recognize **bird**, so there has to be some relations between head and bird. If so, then we could limit the algorithm such that it cannot replace a partition of the graph if doing so would remove the relations. For example, if it tried to recognize "person" instead of "head", it would have to delete some edges in the perception graph, which we can check and block. What do you think?

**Comment by gabbard** [comment]
@denizbeser : Currently in this case `person` would inherit the relationship with `bird`.  I don't think we want to *block* recognition of `person` because then we couldn't say _the bird on the person`, which is also true.

I tentatively think what we want to do here is match both `person` and `head` and introduce nodes for each, and add a `part-of` relationship between the two.  

The trick is to carefully write up the algorithm for doing this.

**Comment by denizbeser** [comment]
**Plan:**
Given hierarchical object perceptions, we currently match one object (e.g either head or person). We instead want to keep both the parent and child matches as options, e.g if we perceive _the bird is on the head_ we want to create a match node for both _head_ and _person_ . This requires changing `match_objects`  (line 177 in `object_recognizer.py` such that in returns an object recognizer with multiple options. Specifically, we use `self._replace_match_with_object_graph_node()` in lne 259 to generates a perception graph with the match node replaced, but we want to create multiple of these instead of breaking after the first match (e.g not stop after matching _person_, but keep on iterating and creating a match for _head_  as well).

This modification also requires us to change the `PerceptionGraphFromObjectRecognizer` class, the type of object we return at the end of `match_objects`. This class currently has one perception graph attribute, but we want to have multiple options. In order to minimize errors across the code base that use instantiations of this class, we can restructure `PerceptionGraphFromObjectRecognizer` such that it stores multiple options (e.g a set of pairs of `perception_graph` and `description_to_matched_object_node`), but returns a single one of them when it's called. E.g, `preprocessing_result.description_to_matched_object_node` in line 76 of `template_learner.py` refers to these attibutes - we can instead use a `description_to_matched_object_node()` method to return a predetermined choice instead.

**Comment by gabbard** [comment]
@denizbeser : can you make the references to particular bits of code links to them on GitHub so I (and others) can more quickly and easily follow your explanations?

**Comment by gabbard** [comment]
I think the way to handle this is as follows:

- when an object is recognized, do not delete it.
- Instead, change only its root object node to be an `ObjectSemanticNode` corresponding to the recognized object.  Note that changing this node really means deleting the old root object node, adding the new one, and connecting it to all the things the old one was connected to with the same edge labels.
