### ISSUE TITLE
English Generator fails to translate "I" in relation as verb

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#605]
We fail to correctly translate "I" as the subject as a sentence: 
("me", "have", "my", "ball")
is a resulting generation of a has(speaker, ball)

**Comment by aakum03** [comment]
@LichMaster98 
I think this has to do with `HAS `being a `RELATION `and not an `ACTION `even though it is a verb. As such, the speaker is never recognized as the `NOMINAL_SUBJECT`, resulting the default `ME ` being used.
Does this need to be a special case?
This seems to fix it, and I don't see any obvious cases where it affects the other parts:
In noun_for_object() in the english_language_generator:
```
# Check if the situation object is the speaker
            if IS_SPEAKER in _object.properties:
                if syntactic_role_if_known == NOMINAL_SUBJECT:
                    noun_lexicon_entry = I
                elif any(relation for relation in self.situation.always_relations if
                         (relation.relation_type == HAS and
                          any(property_ in relation.first_slot.properties
                              for property_ in [IS_SPEAKER]) and
                          len(self.situation.actions) == 0)
                         ):
                    noun_lexicon_entry = I
                else:
                    noun_lexicon_entry = ME
```
NOTE: I only added the elif case

With this, all the test cases containing a `HAS ` relation in test_english_language_generator pass including a test I added:
```
def test_i_have_my_ball():
    baby = situation_object(BABY, properties=[IS_SPEAKER])
    ball = situation_object(BALL)
    situation = HighLevelSemanticsSituation(
        ontology=GAILA_PHASE_1_ONTOLOGY,
        salient_objects=[baby, ball],
        always_relations=[Relation(HAS, baby, ball)],
    )

    assert only(
        _SIMPLE_GENERATOR.generate_language(situation, FixedIndexChooser(0))
    ).as_token_sequence() == ("I", "have", "my", "ball")
```

What do you think?
I haven't submitted a PR/assigned myself since I wasn't sure if you were working on this.
