### ISSUE TITLE
Curriculum for imprecise descriptions

### ISSUE THREAD

**Issue by gabbard** [isi-vista/adam#742]

**Comment by LichMaster98** [comment]
> We therefore plan to learn the remaining frequent words: big, little, tall, short, fast, slow, and (if there is enough time to enhance our temporal reasoning component) new.

# Imprecise Size Descriptions
We plan to implement a curriculum for 4 imprecise size descriptions:
- [ ] Big
- [ ] Little
- [ ] Tall
- [ ] Short

In preparing this curriculum we need to decide how rich of a size environment we want available to our learner as currently, we have three outstanding issues regarding implicit size between objects:

1. [Relative Size Perceptions](#251)
2. [Perceiving All Implicit Size - Not just relative to learner](#215)
3. [Original Issue for Generating Implicit Size and Spatial Relations](#83)

Option 3 also contains a suggested change for the implicit size function. 

The above will become more relevant I suspect when learning rather than at curriculum generation time. 

Our target learner for these descriptions is probably the attribute learner for "big truck", "small ball", etc. However, I could also see examples where we need some type of average or reference for the size information, in the current case I assume that would be the learner. In that case, we may need the hypothesis space of the relationship learner however that would change our text to something closer to "a ball smaller than you" -- We could learn still "small ball" from this relationship but our current implementation wouldn't allow for it.

# Imprecise Temporal Descriptions
We plan to implement at minimum 2 imprecise temporal descriptions:
- [ ] Fast
- [ ] Slow

In order to learn these we are going to modify our `SpatialPath` of an action to contain temporal qualities indicating various different ways of making subtle changes to the primary action.

- [ ] New
Learning new will require adapting a situation, template, and perception to mark an object as *only visible* in one of the two frames of a situation.

**Comment by LichMaster98** [comment]
From our meeting, these thoughts below are also relevant for #743:

These attributes indicate either a situation where there is more than one of the object in the scene, say dogs, that the "big dog" is the biggest from the group of dogs we are looking at while "big dog" with only one dog in the scene implies that the dog is bigger than our prototypical assumption of the size of a dog.

Attributes that can be scalars can get the English "very" added to them. For example "very fast".

These attributes are closer to relationships for our learner capabilities.

Does all of this sound accurate to what we discussed @gabbard, @charles-yang-upenn, and @mitchmarcus ?

**Comment by LichMaster98** [comment]
@denizbeser @gabbard I believe this issue is closed now?

**Comment by gabbard** [comment]
@LichMaster98 : I believe so
