### ISSUE TITLE
Perception Generation fails to translate properties of sub-objects

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#814]
For example a `person` contains the sub-objects of `head, arm, leg, torso` each of these has independent sub-properties as well. `head` for example includes `HOLLOW` 

The lack of translation causes the matcher to be unable to recognize such sub-components in the larger structure.

**Comment by LichMaster98** [comment]
This should be accounted for in this function `_instantiate_object_schema`: https://github.com/isi-vista/adam/blob/ee1cfff3e4b0fde902638ffa56e3714cb26d7791/adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py#L1072 as it is responsible for the perception of sub-objects.

**Comment by spigo900** [comment]
Looking into this, I think the problem is in `_perceive_property_assertions`: https://github.com/isi-vista/adam/blob/c04b20a51313fdbe137b74dcb2dfba9a86211452/adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py#L457 because I notice that `_instantiate_object_schema` doesn't seem to have any logic for creating objects.

I think the problem is happening because it creates the perceived properties by looping over objects in the situation and by looking at properties required by actions. But subobjects aren't explicitly specified in the situation, so they never have their properties added.
