### ISSUE TITLE
Serialize Learner's state to allow for loading a state of the learner for faster debugging

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#883]

**Comment by paynesa** [comment]
For this issue we'll need to do the following:

- [ ] Where we currently log hypotheses, also save the current learner state (probably using pickle). This will allow us to have multiple saved learners at different points in training for debugging. 

- [ ] Add a couple of params regarding whether we want to load an existing learner state or not and whether we want to save the learner state as we train or not.

- [ ] Implement the ability to start learning at a given state, which shouldn't be hard once the above have been implemented.

**Comment by gabbard** [comment]
@paynesa : The only thing I'd add is that we'd like to also be able to serialize the curriculum and our position within it, so we can restart from a particular point in the learning process.  For example, imagine you are consistently getting a crash on instance 637. This is much fast to debug if you can start from a "snapshot" of the process at instance 600.

**Comment by paynesa** [comment]
@gabbard as @LichMaster98 and I discussed, the best way to do this is probably to pass in some sort of number parameter and then calculate which training stage to start at based off of that. The small issue with this is that the calculation isn't simple since we would like to still mark our training stages separately, which means we can't just use direct indexing, but this might be worth what it saves with regards to pickling, especially since there's so much statefulness that needs to be pickled.
