### ISSUE TITLE
SpatialPaths have ambiguity between source and destination which should be resolved

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#932]

**Comment by LichMaster98** [comment]
Currently our `SpatialPath` is made up of an `operator` and a `reference_object` (or region). To solve disambiguation between the source and destination objects the `SpatialPath` should just be refactored to have two 'reference_objects` a `source_object` and `destination_object` 

This will require going through all our situation dictionaries and templates to update for the new structure of the `SpatialPath` which is probably a several hour process.

**Comment by LichMaster98** [comment]
@denizbeser Before I go to implement this solution does it make sense to you?

**Comment by denizbeser** [comment]
@LichMaster98 This makes sense to me. Let me know if you run into any issues!

**Comment by LichMaster98** [comment]
#950 Adds both a source and destination reference object to Spatial Paths. The translation into graphs should be accurate for our representation as the "source" is marked as `BEFORE` and the destination is marked as `AFTER`. 

It may make sense for whoever is going to do this to make notes of any paths they are unsure how to implement and get feedback from 

- [ ] Make sure that both a destination and source are required
- [ ] Go through our internal action dictionaries to update spatial paths (This is a couple of hours task)
- [ ] Go through our curriculum templates to update spatial paths to conform to the new standard (This is also a couple of hours task)
- [ ] Verify learners don't break trying to prune away either a source or destination reference object in action pattern templates.

**Comment by paynesa** [comment]
Using this comment to track things to discuss/uncertainties: 

* For `FALL`, we have an issue with requiring distance or direction in our region since in our curriculum, we currently can either fall from `DISTAL` or `PROXIMAL` but must specify one in the ontology, which leads to an orphaned node corresponding to whichever one we've picked since it's always in the semantics. Example: [slot1_falls_toward_slot2.pdf](https://github.com/isi-vista/adam/files/5085803/slot1_falls_toward_slot2.pdf)
