### ISSUE TITLE
Investigate implementation of an Attribute Pursuit Learner

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#984]

**Comment by denizbeser** [comment]
Just looked at the code again - I don't why this wouldn't be possible. All we need to combine `AbstractPursuitLearnerNew` and `AbstractAttributeTemplateLearnerNew` to create a "PursuitAttributeLearnerNew". For requirements, we can check the existing object version called `PursuitObjectLearnerNew`, and the subset version for attributes called `SubsetAttributeLearnerNew`. I couldn't spot any methods that would cause issues, but my guess is that anything non-object would run much slower since the hypothesis space is much larger compared to just objects (explicitly extracted with `extract_candidate_objects`) or the convergent learning method of intersecting/subsetting hypotheses; I suspect the search space is identical to learning verbs.

**Comment by LichMaster98** [comment]
Ok, @denizbeser Do you have time to do the implementation of this learner or should I factor that into the time it will take me to get this experiment running?

Additionally, If the search space does prove to be an issue we could write an `extract_candidate_attributes` where we explicitly limit the search space (documented) to some restricted set correct? We could artificially say "We will only consider attributes which can be explored with X jumps away from the candidate object being described"?

**Comment by denizbeser** [comment]
@LichMaster98 I'm busy with a couple of semantics experiments - can you work on it and I can jump in to help if you run into any issues? 
Yes, we should indeed trim the space with a specific extraction function, just like we did for obhects. We would need to discuss it's requirements though. Let's slack about meeting to discuss that.

**Comment by LichMaster98** [comment]
Sounds good. Thanks for looking into this for me.
